name: Run Instagram Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Manual Checkout repository
      run: |
        git clone https://github.com/${{ github.repository }}.git .
        git checkout ${{ github.ref_name }}

    - name: Manual Set up Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        python3 -m pip install --upgrade pip

    - name: Fix urllib3 and six compatibility
      run: |
        pip install --upgrade urllib3==1.26.18
        pip install --upgrade six
        pip install --upgrade requests

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Set up virtual display for headless browser
      run: |
        sudo apt-get install -y xvfb
        pip install pyvirtualdisplay

    - name: Run Instagram Bot
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        python3 botAccountCreate.py

